log:
  level: "debug"

http:
  port: "2021"
  api:
    path: "api"

db:
  mysql:
    host: "tcp(10.143.15.226:3306)"
    user: "root"
    password: "root"
    dbname: "fsender2"

upload:
  file: "./upload/files/"
  log: "./upload/logs/"

task:
  concurrent: 10
  conf:
    concurrent: 100
